-- Enable pgcrypto for UUID generation
create extension if not exists pgcrypto;

-- ------------------------
-- Customers Table
-- ------------------------
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text,
  wilaya text,
  delivery_method text,
  carrier text,
  pickup_location text,
  notes text,
  created_at timestamp default now()
);

-- ------------------------
-- Orders Table
-- ------------------------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete cascade,
  subtotal integer not null,
  shipping integer not null,
  total integer not null,
  status text default 'pending',
  created_at timestamp default now()
);

-- ------------------------
-- Order Items Table
-- ------------------------
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete cascade,
  product_id integer references public.products(id) on delete cascade,
  quantity integer not null,
  price_at_time integer not null
);

-- ------------------------
-- Shipping Rates Table
-- ------------------------
create table if not exists public.shipping_rates (
  id bigint generated by default as identity primary key,
  wilaya text not null unique,
  home integer not null,
  desk integer not null,
  created_at timestamp default now()
);

-- ------------------------
-- Enable Row-Level Security
-- ------------------------
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.products enable row level security;
alter table public.shipping_rates enable row level security;

-- ------------------------
-- Allow anon & authenticated roles to use schema
-- ------------------------
grant usage on schema public to anon, authenticated;

-- ------------------------
-- Table policies
-- ------------------------

-- Customers
drop policy if exists customers_insert_policy on public.customers;
create policy customers_insert_policy
  on public.customers
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists customers_select_policy on public.customers;
create policy customers_select_policy
  on public.customers
  for select
  to anon, authenticated
  using (true);

drop policy if exists customers_update_policy on public.customers;
create policy customers_update_policy
  on public.customers
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists customers_delete_policy on public.customers;
create policy customers_delete_policy
  on public.customers
  for delete
  to anon, authenticated
  using (true);

-- Orders
drop policy if exists orders_insert_policy on public.orders;
create policy orders_insert_policy
  on public.orders
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists orders_select_policy on public.orders;
create policy orders_select_policy
  on public.orders
  for select
  to anon, authenticated
  using (true);

drop policy if exists orders_update_policy on public.orders;
create policy orders_update_policy
  on public.orders
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists orders_delete_policy on public.orders;
create policy orders_delete_policy
  on public.orders
  for delete
  to anon, authenticated
  using (true);

-- Order Items
drop policy if exists order_items_insert_policy on public.order_items;
create policy order_items_insert_policy
  on public.order_items
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists order_items_select_policy on public.order_items;
create policy order_items_select_policy
  on public.order_items
  for select
  to anon, authenticated
  using (true);

-- Products Table
drop policy if exists products_select_policy on public.products;
create policy products_select_policy
  on public.products
  for select
  to anon, authenticated
  using (true);

drop policy if exists products_insert_policy on public.products;
create policy products_insert_policy
  on public.products
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists products_update_policy on public.products;
create policy products_update_policy
  on public.products
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists products_delete_policy on public.products;
create policy products_delete_policy
  on public.products
  for delete
  to anon, authenticated
  using (true);

-- Shipping rates
drop policy if exists shipping_rates_select_policy on public.shipping_rates;
create policy shipping_rates_select_policy
  on public.shipping_rates
  for select
  to anon, authenticated
  using (true);

drop policy if exists shipping_rates_insert_policy on public.shipping_rates;
create policy shipping_rates_insert_policy
  on public.shipping_rates
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists shipping_rates_update_policy on public.shipping_rates;
create policy shipping_rates_update_policy
  on public.shipping_rates
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists shipping_rates_delete_policy on public.shipping_rates;
create policy shipping_rates_delete_policy
  on public.shipping_rates
  for delete
  to anon, authenticated
  using (true);

-- ------------------------
-- Storage bucket
-- ------------------------

-- Create products bucket if not exists
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do nothing;

-- Public read for everyone
drop policy if exists products_bucket_public_read on storage.objects;
create policy products_bucket_public_read
  on storage.objects
  for select
  to public
  using (bucket_id = 'products');

-- Allow insert/update/delete by anon & authenticated in products bucket
drop policy if exists products_bucket_anon_insert on storage.objects;
create policy products_bucket_anon_insert
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'products');

drop policy if exists products_bucket_anon_update on storage.objects;
create policy products_bucket_anon_update
  on storage.objects
  for update
  to anon, authenticated
  using (bucket_id = 'products')
  with check (bucket_id = 'products');

drop policy if exists products_bucket_anon_delete on storage.objects;
create policy products_bucket_anon_delete
  on storage.objects
  for delete
  to anon, authenticated
  using (bucket_id = 'products');